# Generated by Django 4.1.1 on 2022-09-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='название')),
                ('description', models.CharField(max_length=30, verbose_name='описание')),
                ('can_move', models.BooleanField(verbose_name='на ходу')),
            ],
            options={
                'verbose_name': 'транспорт',
                'verbose_name_plural': 'транспорт',
                'ordering': ('name', '-can_move'),
            },
        ),
    ]
